name: Azure Static Web Apps CI/CD

trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

jobs:
- job: build_and_deploy_job
  displayName: Build and Deploy Frontend (SWA)
  pool:
    vmImage: ubuntu-latest

  variables:
  - group: Azure-Static-Web-Apps-gray-island-0de03d10f-variable-group

  steps:
  - checkout: self

  - task: AzureStaticWebApp@0
    inputs:
      azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN_GRAY_ISLAND_0DE03D10F)
      app_location: "frontend"
      api_location: ""
      output_location: "dist"
    env:
      VITE_REALTIME_HTTP: https://chatt-realtime.yellowdesert-835dd921.eastus2.azurecontainerapps.io
      VITE_REALTIME_WS: wss://chatt-realtime.yellowdesert-835dd921.eastus2.azurecontainerapps.io/voice/ws

      VITE_ORCH_HTTP: https://chatt-orchestrator.yellowdesert-835dd921.eastus2.azurecontainerapps.io
      VITE_ORCH_CONTROL_WS: wss://chatt-orchestrator.yellowdesert-835dd921.eastus2.azurecontainerapps.io/v1/control

      VITE_STT_WS: wss://chatt-speech.yellowdesert-835dd921.eastus2.azurecontainerapps.io/stt/ws
