FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    ca-certificates \
    libsndfile1 \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app_realtime.py .
COPY audio_utils.py .
COPY instructions.json .
#COPY .env .

EXPOSE 50505

CMD ["uvicorn", "app_realtime:app", "--host", "0.0.0.0", "--port", "50505"]
