import os

# Azure OpenAI / Foundry
AZURE_OPENAI_ENDPOINT = os.getenv("AZURE_OPENAI_ENDPOINT", "").rstrip("/")
AZURE_OPENAI_KEY = os.getenv("AZURE_OPENAI_KEY", "")
AZURE_OPENAI_MODEL = os.getenv("AZURE_OPENAI_MODEL", "gpt-4o-mini")
AZURE_OPENAI_API_VERSION = os.getenv(
    "AZURE_OPENAI_API_VERSION", "2025-05-01-preview"
)

# Agent 1 behavior
AGENT1_TIMEOUT_SECONDS = 8
AGENT1_MAX_QUESTIONS = 5
AGENT1_MAX_QUESTION_LENGTH = 300
